#!/bin/sh

while read file
do
    case "$1" in
        #"C-d")
        #    mv "$file" ~/.trash ;;
        #"C-r")
        #    convert -rotate 90 "$file" "$file" ;;
        "C-c")
            echo "$file" | xclip -selection clipboard ;;
        "i")
            # jpeg info
            echo "$file:"
            jhead "$file" ;;
        #"C-w")
        #    nitrogen --save --set-zoom-fill "$file" ;;
    esac
done
